esphome/firmware

esp-web-tools/esp32.yaml
esp-web-tools/esp8266.yaml

For https://github.com/esphome/esp-web-tools/pull/87

Add demo configs for ESP Web Tools

---

esphome-web/esp32.yaml
esphome-web/esp8266.yaml

- Add `full_import_config` to enable importing the full configuration

Update ESPHome Web config

---

.github/workflows/build.yml
esphome-web/esp32.yaml
esphome-web/esp8266.yaml
esphome-web/pico-w.yaml

Add a firmware for Pico for ESPHome Web

Build ESPHome Web firmware for Pico W

---

esp-web-tools/esp32.yaml
esp-web-tools/esp32c3.yaml
esp-web-tools/esp32s2.yaml
esp-web-tools/esp32s3.yaml
esp-web-tools/esp8266.yaml
esphome-web/esp32.yaml
esphome-web/esp32c3.yaml
esphome-web/esp32s2.yaml
esphome-web/esp32s3.yaml
esphome-web/esp8266.yaml
esphome-web/pico-w.yaml

https://github.com/esphome/esphome/pull/4296

Add friendly_name

---

voice-assistant/m5stack-atom-echo.yaml

- Adds speaker
- Removes media player
- Changes to esp-idf
- adds a pulse effect for the led
- changes led to native rmt driver

Updates for 2023.5.0

---

.github/workflows/build.yml
bluetooth-proxy/esp32-generic.yaml
bluetooth-proxy/gl-s10.yaml
bluetooth-proxy/lilygo-t-eth-poe.yaml
bluetooth-proxy/m5stack-atom-lite.yaml
bluetooth-proxy/olimex-esp32-poe-iso.yaml
bluetooth-proxy/wt32-eth01.yaml

These files are copies of the files in https://esphome/bluetooth-proxies except for updating the dashboard_import url to point to this repo

Add bluetooth-proxy configurations

---

.github/workflows/build.yml
media-player/m5stack-atom-echo.yaml
media-player/m5stack-atom-speaker-kit.yaml
media-player/raspiaudio-muse-luxe.yaml
media-player/raspiaudio-muse-proto.yaml

These files are copies of the files in https://esphome/media-players with the following exceptions:
- dashboard_import url changed to point to this repo
- substitutions removed to tidy up the files

Add media-player configurations

---

voice-assistant/esp32-s3-box-lite.yaml
voice-assistant/esp32-s3-box.yaml
voice-assistant/quinled-dig2go.yaml
voice-assistant/raspiaudio-muse-luxe.yaml
voice-assistant/raspiaudio-muse-proto.yaml

Add audio processing to voice assistant firmwares.
```yaml
noise_suppression_level: 2
auto_gain: 31dBFS
volume_multiplier: 2.0
vad_threshold: 3
```

Add basic audio processing to voice assistant firmwares

---

voice-assistant/esp32-s3-box-lite.yaml
voice-assistant/esp32-s3-box.yaml
voice-assistant/m5stack-atom-echo.yaml
voice-assistant/quinled-dig2go.yaml
voice-assistant/raspiaudio-muse-luxe.yaml
voice-assistant/raspiaudio-muse-proto.yaml

Apply sentence-style capitalization

Wake word string: apply sentence-style capitalization

---

bluetooth-proxy/gl-s10.yaml

Minor change updating code line references in docs.

gl-s10 correct comment code line references

---

voice-assistant/esp32-s3-box-lite.yaml
voice-assistant/esp32-s3-box.yaml
voice-assistant/m5stack-atom-echo.yaml
voice-assistant/quinled-dig2go.yaml
voice-assistant/raspiaudio-muse-luxe.yaml
voice-assistant/raspiaudio-muse-proto.yaml

- Make wake word switch a config entity
- Disable binary sensors by default

A few minor config updates

---

voice-assistant/raspiaudio-muse-proto.yaml

Fixes https://github.com/esphome/issues/issues/4976

Fix mute pin not implemented in RaspiAudio Muse Proto

---

voice-assistant/esp32-s3-box-lite.yaml
voice-assistant/esp32-s3-box.yaml
voice-assistant/quinled-dig2go.yaml
voice-assistant/raspiaudio-muse-luxe.yaml
voice-assistant/raspiaudio-muse-proto.yaml

Same as https://github.com/esphome/firmware/pull/83 but for the rest of the devices

Start voice assistant on api connection part 2

---

media-player/onju-voice.yaml

Add the Onju Voice (https://github.com/justLV/onju-voice) as a media player/voice assistant
Source of the config: https://gist.github.com/tetele/75815c53cfd2a02412ef153f9c2d24e2 tested and improved for a few days

Added Onju Voice as a supported media player

---

.github/workflows/build.yml
voice-assistant/esp32-s3-box-lite.yaml
voice-assistant/esp32-s3-box.yaml
voice-assistant/m5stack-atom-echo.yaml
voice-assistant/quinled-dig2go.yaml
voice-assistant/raspiaudio-muse-luxe.yaml
voice-assistant/raspiaudio-muse-proto.yaml

These errors have been moved to be [handled internally](https://github.com/esphome/esphome/pull/5738) inside the Voice Assistant
Requires ESPHome 2023.11.0b5 to be released before merging.

Handle wake errors internally

---

.github/workflows/build.yml

This *should* only run a build of a firmware if it changed, was added, or the entire workflow file was modified

Attempt to only run CI on added/changed yaml files

---

voice-assistant/esp32-s3-box-3.yaml
voice-assistant/esp32-s3-box-lite.yaml
voice-assistant/esp32-s3-box.yaml

ESPHome 2023.11.4 introduces remote images that are downloaded at compile time and cached in the ESPHome data directory

Use remote image url

---

.github/workflows/build.yml

https://github.com/esphome/build-action/releases/tag/v1.9.0

Bump esphome/build-action to 1.9.0

---

.github/workflows/build.yml

Since the stable release is out, we can go back to stable now.

Dont build VA with beta anymore

---

.github/workflows/build.yml

Requires:
- https://github.com/esphome/build-action/pull/33

Deploy ota images with updated manifests

---

.github/workflows/build.yml
bluetooth-proxy/esp32-generic-c3.yaml
bluetooth-proxy/esp32-generic.yaml
bluetooth-proxy/gl-s10.yaml
bluetooth-proxy/lilygo-t-eth-poe.yaml
bluetooth-proxy/m5stack-atom-lite.yaml
bluetooth-proxy/m5stack-atomS3.yaml
bluetooth-proxy/olimex-esp32-poe-iso.yaml
bluetooth-proxy/wt32-eth01.yaml
media-player/m5stack-atom-echo.yaml
media-player/m5stack-atom-speaker-kit.yaml
media-player/onju-voice.yaml
media-player/raspiaudio-muse-luxe.yaml
media-player/raspiaudio-muse-proto.yaml
voice-assistant/esp32-s3-box-3.yaml
voice-assistant/esp32-s3-box-lite.yaml
voice-assistant/esp32-s3-box.yaml
voice-assistant/m5stack-atom-echo.yaml
voice-assistant/quinled-dig2go.yaml
voice-assistant/raspiaudio-muse-luxe.yaml
voice-assistant/raspiaudio-muse-proto.yaml
wake-word-voice-assistant/esp32-s3-box-3.yaml
wake-word-voice-assistant/esp32-s3-box-lite.yaml
wake-word-voice-assistant/esp32-s3-box.yaml
wake-word-voice-assistant/m5stack-atom-echo.yaml

Adding the new `update` entities to our provided firmwares.
This will also move each project to have their own version.

Add ota update to all project firmwares

---

wake-word-voice-assistant/esp32-s3-box-3.yaml
wake-word-voice-assistant/esp32-s3-box-lite.yaml
wake-word-voice-assistant/esp32-s3-box.yaml

**Removed**
- All the hidden entities related to button presses
- The Factory reset button on HA (Still available as a 10-s press)
- The Safe Mode button
**Added**
- Icons and better names to a few entities (Screen, Mute, Wake Word Engine Location)

Simplify S3 Box Firmwares

---

wake-word-voice-assistant/esp32-s3-box-3.yaml
wake-word-voice-assistant/esp32-s3-box-lite.yaml
wake-word-voice-assistant/esp32-s3-box.yaml

This should had been done in #236 that switched from model to models for micro_wake_word

Update min_version to 2024.7.0

---

wake-word-voice-assistant/esp32-s3-box-3.yaml
wake-word-voice-assistant/esp32-s3-box-lite.yaml
wake-word-voice-assistant/esp32-s3-box.yaml

Before if you pressed mute while voice assistant is running, micro_wake_word would still start after voice assistant ends.

Fix pressing mute while voice assistant is running

---

wake-word-voice-assistant/esp32-s3-box-3.yaml
wake-word-voice-assistant/esp32-s3-box-lite.yaml
wake-word-voice-assistant/esp32-s3-box.yaml
wake-word-voice-assistant/m5stack-atom-echo.yaml

This will build with ESPHome 2024.7.3
The YAML files are going to be "moved" to their own repo soon and versioning will become more clear.

Bump wwva to 24.8.1

---

voice-assistant/m5stack-atom-echo.adopted.yaml
voice-assistant/m5stack-atom-echo.yaml
voice-assistant/raspiaudio-muse-luxe.yaml
voice-assistant/raspiaudio-muse-proto.yaml

Updates for ESPHome 2024.9.0

---

esphome-web/pico-w.yaml

to match https://github.com/esphome/esphome/pull/7507

fix rp2040 build break

---

voice-assistant/esp32-s3-box-3.yaml
voice-assistant/esp32-s3-box-lite.yaml
voice-assistant/esp32-s3-box.yaml

Adds `invert_colors: false` to display component so that firmware will build.

Fix voice-assistant display configs

---

.github/workflows/build.yml
esphome-web/esp32.factory.yaml
esphome-web/esp32.yaml
esphome-web/esp32c3.factory.yaml
esphome-web/esp32c3.yaml
esphome-web/esp32s2.factory.yaml
esphome-web/esp32s2.yaml
esphome-web/esp32s3.factory.yaml
esphome-web/esp32s3.yaml
esphome-web/esp8266.factory.yaml
esphome-web/esp8266.yaml
esphome-web/pico-w.factory.yaml
esphome-web/pico-w.yaml

This splits the esphome-web configs to factory and minimal for taking control

Split esphome-web to use factory
