esphome/firmware

esp-web-tools/esp32.yaml, esp-web-tools/esp8266.yaml
This allows it to be picked up as "NEXT URL" for Improv Serial and unlocking that option in ESP Web Tools.
=> Add web server to ESP Web Tools configs

.github/workflows/build.yml, voice-assistant/esp32-s3-box.yaml
Once merged, the manifest will be available at https://firmware.esphome.io/voice-assistant/esp32-s3-box/manifest.json
=> Add esp32-s3-box voice assistant configuration

voice-assistant/esp32-s3-box-lite.yaml, voice-assistant/esp32-s3-box.yaml, voice-assistant/m5stack-atom-echo.yaml, voice-assistant/quinled-dig2go.yaml, voice-assistant/raspiaudio-muse-luxe.yaml, voice-assistant/raspiaudio-muse-proto.yaml
`wake-provider-missing` was already handled but `wake-engine-missing` was not, causing a very fast and infinite loop of pipeline starts and stops if the wake-word switch was on inside esphome.
=> Fix missing wake engine handling

.github/workflows/build.yml
The matrix was getting messy with many individual `include` lines, this changes that so that we only need to alter the `FIRMWARES` env var to build all firmwares for that folder.
=> Auto populate matrix build from files inside directories

media-player/m5stack-atom-echo.yaml
Stop playing any media before starting listening.
When long-pressing the button while a command result is playing, STT fails because of the noise from the internal speaker at the same time we talk.
If nothing is playing, voice_assistant starts directly.
=>     Stop media player before starting voice assistant in m5stack-atom-echo

voice-assistant/m5stack-atom-echo.yaml
Added switch to enable or disable the listen light, could be useful if you have the device in the bedroom for example, and want to turn off the light at night.
(or if you just don't want the light at all).
=> Add switch for listen light

voice-assistant/m5stack-atom-echo.yaml
This is a basic way to attempt to restart the voice asssistant with the downside that it will not work correctly if the logs are being followed over the air as this uses the `api` server too
=> Start voice assistant on api connection

voice-assistant/esp32-s3-box-lite.yaml, voice-assistant/esp32-s3-box.yaml, voice-assistant/m5stack-atom-echo.yaml, voice-assistant/quinled-dig2go.yaml, voice-assistant/raspiaudio-muse-luxe.yaml, voice-assistant/raspiaudio-muse-proto.yaml
Today if the ESPHome Voice Assistant gets disconnected to Home Assistant, or if it's never integrated into Home Assistant, the light stays Purple as if the device was ready to listen to wake words.
This PR fixes that.
The LED only turns on (using `script.execute: reset_led` when the client is connected, and turns off when it's disconnected)
This means that the purple light is now aligned with the fact that the device is ready to listen to a wake word.
For example, during a HA update, you will see your voice assistant LED turning off because the server is not ready.
=> Stop led on disconnect, reset LED on connect

.github/workflows/build.yml
The option `new_install_skip_erase` is deprecated in ESP Web Tools. We also set it to the default value so there is no value in setting it. This PR removes it.
=> Remove deprecated new_install_skip_erase from manifest

esp-web-tools/esp32s2.yaml, esp-web-tools/esp32s3.yaml, esphome-web/esp32s2.yaml, esphome-web/esp32s3.yaml
For Arduino builds on the `S` variants, we need:
```yaml
platformio_options:
board_build.flash_mode: dio
```
...to avoid a boot loop.
=> Set DIO flash mode for S-variants

bluetooth-proxy/wt32-eth01.yaml
Platform.io has an explicit profile for this module: https://docs.platformio.org/en/latest/boards/espressif32/wt32-eth01.html
=> Use board setting for wt32-eth01

voice-assistant/m5stack-atom-echo.yaml, voice-assistant/quinled-dig2go.yaml, voice-assistant/raspiaudio-muse-luxe.yaml, voice-assistant/raspiaudio-muse-proto.yaml
For each of the 4 voice assistant boards with LEDs as visual feedback
I created two effects 
- A "Slow Pulse" for when the device is Listening
- A "Fast Pulse" for when the device is "Processing"
Note that I considered the beginning of the Processing `on_stt_vad_end` so that users with slow STT engine are included
I kept @kbx81 "Warm white settings" for the idle state
=> New color scheme for voice assistant

voice-assistant/esp32-s3-box-3.yaml, voice-assistant/esp32-s3-box-lite.yaml, voice-assistant/esp32-s3-box.yaml, voice-assistant/m5stack-atom-echo.yaml, voice-assistant/raspiaudio-muse-luxe.yaml, voice-assistant/raspiaudio-muse-proto.yaml
This PR adds `esp32_improv` via ble to the configs to allow provisioning Wi-Fi directly from Home Assistant with `bluetooth_proxies`
It also adds a factory reset virtual and hardware button.
The same button used for stopping the Voice Assistant can be held for 10 seconds to factory reset (Remove Wi-Fi credentials)
Device | Added | Tested
-------|-------|-------
Atom Echo | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
S3 Box | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
S3 Box Lite | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
S3 Box 3 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
Muse Proto | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
Muse Luxe | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
=> Add ble improv and factory reset to VA

voice-assistant/esp32-s3-box-3.yaml, voice-assistant/esp32-s3-box-lite.yaml, voice-assistant/esp32-s3-box.yaml
With the removal of the "Push to talk" functionality on the Boxes, the switch. "Use Wake Word" makes little sense,
So I am renaming it to "Mute"
=> Rename Use Wake Word to Mute

voice-assistant/esp32-s3-box-3.yaml, voice-assistant/esp32-s3-box-lite.yaml, voice-assistant/esp32-s3-box.yaml
I made a mistake on https://github.com/esphome/firmware/pull/122
I renamed the switch from Use Wake Word to Mute but forgot to invert it.
The behavior today is very confusing has you need to `turn_off` Mute to Mute the device.
Sorry about the confusion, this PR solves this.
=> Inverse the Mute Switch Behavior

.github/workflows/build.yml
Change the ESP Web Tools manifest name to "ESP Web Tools Example" as you are not installing "ESP Web Tools" but an example firmware.
Noticed that there is one downside to setting the name in general. The name of the firmware needs to match the name returned from Improv to offer upgrades to the user. However, ESPHome always returns "ESPHome". But that's for another PR.
=> Update name of ESP Web Tools firmware

.github/workflows/build.yml, voice-assistant/esp32-s3-box-3.yaml, voice-assistant/esp32-s3-box-lite.yaml, voice-assistant/esp32-s3-box.yaml
* Configuration selector to change the wake word engine location
* Ability to switch wake word engine location in the middle of the pipeline run, the device waits the end of the pipeline and switches engine seamlessly.
* Default wake word for micro wake word as a substitution for customization
=> Micro wake word integration in S3 Box firmware

voice-assistant/esp32-s3-box-3.yaml, voice-assistant/esp32-s3-box-lite.yaml, voice-assistant/esp32-s3-box.yaml, wake-word-voice-assistant/esp32-s3-box-3.yaml, wake-word-voice-assistant/esp32-s3-box-lite.yaml, wake-word-voice-assistant/esp32-s3-box.yaml
The idea is coming from the Voice Assistant Contest.
Credit to [user Lajos and his entry](https://community.home-assistant.io/t/a-jrpg-style-conversation-with-the-voice-assistant-on-the-s3-box-3/697172). 
**Spoken text is displayed on the box during the thinking phase**
**Response text is displayed on the box during the replying phase**
This behavior is user-configurable via a switch called `Display conversation` on Home Assistant.
The value of the switch is restored, but `ON` by default if no value is found (It will be `ON` when updating for the first time)
In ESPHome, we need to load what character we are planning to display.
Because the firmware is supposed to be used by all our supported languages, I searched for a proxy that would be a good approximation of every character that we …
=> Text on S3 Boxes

voice-assistant/m5stack-atom-echo.yaml
Timers on them5Stack Atom Echos
When a timer ends, two things happen
- The LED flashes green
- A sound plays until the button is pressed
**Q&A**
- Can a user change the beep sound?
- Not in this version, I needed to know the length of the .wav file to loop it. If I can find a way to circumvent that, I may allow users to change sounds.
- If a user ignores the end of the timer, will the box ring forever?
- No, it will ring for 15 minutes then stop. We built that guardrail in the firmware.
```yaml
file:
- id: timer_finished_wave_file
#path: https://github.com/esphome/firmware/raw/main/voice-assistant/sounds/timer_finished.wav TO BE FIXED ONCE `file` SUPPORTS REMOTE PATH
path: ..//voice-assistant/sounds/timer_finished.wav
```
=> Timers on M5STACK ATOM ECHO

wake-word-voice-assistant/esp32-s3-box-3.yaml, wake-word-voice-assistant/esp32-s3-box-lite.yaml, wake-word-voice-assistant/esp32-s3-box.yaml
The `micro_wake_word.start` that was under `on_value` of the select `wake_word_engine_location` was triggered during start-up even if the box was supposed to be muted.
This led to a box in a weird state: 
- Back screen as if it was muted
- Still able to wake it up
I made that `on_value` more robust.
I added a condition on `init_in_progress` (because nothing should happen in that stage anyway)
More importantly, I added a `mute` condition when the value changed to `On Device` to avoid starting micro_wake_word when the device is muted.
=> Fix Mute State during start-up on the boxes

bluetooth-proxy/esp32-generic-c3.yaml, bluetooth-proxy/esp32-generic.yaml, bluetooth-proxy/gl-s10.yaml, bluetooth-proxy/lilygo-t-eth-poe.yaml, bluetooth-proxy/m5stack-atom-lite.yaml, bluetooth-proxy/m5stack-atomS3.yaml, bluetooth-proxy/olimex-esp32-poe-iso.yaml, bluetooth-proxy/wt32-eth01.yaml, media-player/m5stack-atom-echo.yaml, media-player/m5stack-atom-speaker-kit.yaml, media-player/onju-voice.yaml, media-player/raspiaudio-muse-luxe.yaml, media-player/raspiaudio-muse-proto.yaml, voice-assistant/esp32-s3-box-3.yaml, voice-assistant/esp32-s3-box-lite.yaml, voice-assistant/esp32-s3-box.yaml, voice-assistant/m5stack-atom-echo.yaml, voice-assistant/quinled-dig2go.yaml, voice-assistant/raspiaudio-muse-luxe.yaml, voice-assistant/raspiaudio-muse-proto.yaml, wake-word-voice-assistant/esp32-s3-box-3.yaml, wake-word-voice-assistant/esp32-s3-box-lite.yaml, wake-word-voice-assistant/esp32-s3-box.yaml
This allows adopted configs to override/extend any configurations we have provided without losing the link to the provided remote package
=> Add ids to all entities

.github/workflows/build.yml
Because we now have to bump the versions in files, we should release properly with tags/releases.
=> Publish firmware only on release tags

wake-word-voice-assistant/esp32-s3-box-3.yaml, wake-word-voice-assistant/esp32-s3-box-lite.yaml, wake-word-voice-assistant/esp32-s3-box.yaml
Took me a while to figure out why the on-device wake word was no longer working after a restart until I muted & unmuted.  My understanding is that the `use_wake_word` config is for detecting audio with the esp-adf libraries & VAD then sending the audio data through the pipeline to be processed by openWakeWord.  Unfortunately this conflicts with microWakeWord processed locally.
Seems to have been surfaced after the otherwise helpful https://github.com/esphome/firmware/pull/214.  Before, the `on_value` automation in `wake_word_engine_location` would run `set_use_wake_word(false)` at boot when it's configured for On device detection.  Now with the `init_in_progress` check, that doesn't run and is initially left on.
Here's a potential fix that also removes the `use_wake_word` config, …
=> Disable openWakeWord when using microWakeWord

wake-word-voice-assistant/m5stack-atom-echo.adopted.yaml, wake-word-voice-assistant/m5stack-atom-echo.yaml
Micro wake word 2 is possible on the M5 Stack Atom Echo since 2024.7.0
However it's end of speech detection was affected greatly by the issue fixed in https://github.com/esphome/esphome/pull/7109 so this version targets 2024.7.1
This firmware is adapted from `https://github.com/esphome/firmware/blob/main/voice-assistant/m5stack-atom-echo.yaml`
There are some notable changes:
- Micro wake word 2 is enabled, with a default of 'okay_nabu'.
- The `use_wake_word` toggle that used to switch between steamed audio to 'click to converse' is replaced by a toggle `use_micro_wake_word` that switches between micro wake word and steamed audio.
- No more click to converse
- A new teal light colour when not using micro_wake_word
- Removed improv ble as
```
Error: The program size (2104013 bytes) is …
```
=> New micro wake word 2 `m5stack-atom-echo.yaml`
